# Generated by Django 5.1.4 on 2026-07-13 08:59

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_key', models.CharField(blank=True, db_index=True, help_text="DİA ERP'deki kaydın _key değeri. Henüz senkronize edilmediyse boş.", max_length=50, null=True, unique=True, verbose_name='DİA Key')),
                ('son_sync_tarihi', models.DateTimeField(blank=True, null=True, verbose_name='Son senkronizasyon')),
                ('sync_durumu', models.CharField(choices=[('senkron', 'Senkron (DİA ile uyumlu)'), ('bekliyor', 'Bekliyor (senkronize edilmedi)'), ('isleniyor', 'İşleniyor'), ('hatali', 'Hatalı (son sync başarısız)'), ('yerel', "Yerel değişiklik var (DİA'ya yazılmadı)")], db_index=True, default='bekliyor', max_length=20, verbose_name='Sync durumu')),
                ('dia_son_degisiklik', models.DateTimeField(blank=True, help_text='DİA _date alanından alınan son güncelleme zamanı (delta sync için)', null=True, verbose_name="DİA'da son değişiklik")),
                ('cari_kodu', models.CharField(help_text="DİA carikartkodu. Otomatik atanır veya DİA'dan senkronize edilir.", max_length=30, unique=True, verbose_name='Cari kodu')),
                ('unvan', models.CharField(max_length=200, verbose_name='Ünvan')),
                ('kisa_aciklama', models.CharField(blank=True, max_length=100, verbose_name='Kısa açıklama')),
                ('tip', models.CharField(choices=[('AL', 'Alıcı (Müşteri)'), ('SA', 'Satıcı (Tedarikçi)'), ('AS', 'Alıcı/Satıcı'), ('D', 'Diğer')], default='AL', max_length=2, verbose_name='Cari tipi')),
                ('durum', models.CharField(choices=[('A', 'Aktif'), ('P', 'Pasif')], default='A', max_length=1, verbose_name='Durum')),
                ('vergi_no', models.CharField(blank=True, max_length=20, verbose_name='Vergi numarası')),
                ('tc_kimlik_no', models.CharField(blank=True, max_length=11, verbose_name='TC kimlik no')),
                ('vergi_dairesi', models.CharField(blank=True, max_length=100, verbose_name='Vergi dairesi')),
                ('daire_kodu', models.CharField(blank=True, max_length=20, verbose_name='Daire kodu')),
                ('telefon1', models.CharField(blank=True, max_length=30, verbose_name='Telefon 1')),
                ('telefon2', models.CharField(blank=True, max_length=30, verbose_name='Telefon 2')),
                ('cep_tel', models.CharField(blank=True, max_length=30, verbose_name='Cep telefonu')),
                ('fax', models.CharField(blank=True, max_length=30, verbose_name='Faks')),
                ('eposta', models.EmailField(blank=True, max_length=254, verbose_name='E-posta')),
                ('web_url', models.URLField(blank=True, max_length=300, verbose_name='Web sitesi')),
                ('adres1', models.CharField(blank=True, max_length=200, verbose_name='Adres 1')),
                ('adres2', models.CharField(blank=True, max_length=200, verbose_name='Adres 2')),
                ('ilce', models.CharField(blank=True, max_length=100, verbose_name='İlçe')),
                ('sehir', models.CharField(blank=True, max_length=100, verbose_name='Şehir')),
                ('posta_kodu', models.CharField(blank=True, max_length=10, verbose_name='Posta kodu')),
                ('ulke', models.CharField(blank=True, default='TÜRKİYE', max_length=100, verbose_name='Ülke')),
                ('risk_limiti', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18, verbose_name='Risk limiti')),
                ('indirim_orani', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=7, verbose_name='İndirim oranı (%)')),
                ('bakiye', models.DecimalField(decimal_places=4, default=Decimal('0'), help_text="DİA'dan senkronize edilen anlık bakiye. MEStakip hesaplamaz.", max_digits=18, verbose_name="Bakiye (DİA'dan)")),
                ('borc_toplam', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18, verbose_name='Borç toplamı')),
                ('alacak_toplam', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18, verbose_name='Alacak toplamı')),
                ('efatura_senaryosu', models.CharField(blank=True, help_text='DİA efaturasenaryosu: 0=Temel, 1=Ticari vb.', max_length=10, verbose_name='e-Fatura senaryosu')),
                ('notlar', models.TextField(blank=True, verbose_name='Notlar')),
                ('olusturuldu', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturuldu')),
                ('guncellendi', models.DateTimeField(auto_now=True, verbose_name='Güncellendi')),
            ],
            options={
                'verbose_name': 'Cari',
                'verbose_name_plural': 'Cariler',
                'ordering': ['unvan'],
                'indexes': [models.Index(fields=['cari_kodu'], name='erp_cari_cari_ko_b42e5e_idx'), models.Index(fields=['vergi_no'], name='erp_cari_vergi_n_2c1260_idx'), models.Index(fields=['tip', 'durum'], name='erp_cari_tip_8435cd_idx'), models.Index(fields=['unvan'], name='erp_cari_unvan_5e46f5_idx')],
            },
        ),
    ]
