# Generated by Django 5.1.4 on 2026-07-13 09:17

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Depo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_key', models.CharField(max_length=20, unique=True, verbose_name='DİA Depo Key')),
                ('ad', models.CharField(max_length=100, verbose_name='Depo adı')),
                ('sube_adi', models.CharField(blank=True, max_length=100, verbose_name='Şube adı')),
                ('sube_dia_key', models.CharField(blank=True, max_length=20, verbose_name='DİA Şube Key')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('olusturuldu', models.DateTimeField(auto_now_add=True)),
                ('guncellendi', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Depo',
                'verbose_name_plural': 'Depolar',
                'ordering': ['sube_adi', 'ad'],
            },
        ),
        migrations.CreateModel(
            name='StokKart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_key', models.CharField(blank=True, db_index=True, help_text="DİA ERP'deki kaydın _key değeri. Henüz senkronize edilmediyse boş.", max_length=50, null=True, unique=True, verbose_name='DİA Key')),
                ('son_sync_tarihi', models.DateTimeField(blank=True, null=True, verbose_name='Son senkronizasyon')),
                ('sync_durumu', models.CharField(choices=[('senkron', 'Senkron (DİA ile uyumlu)'), ('bekliyor', 'Bekliyor (senkronize edilmedi)'), ('isleniyor', 'İşleniyor'), ('hatali', 'Hatalı (son sync başarısız)'), ('yerel', "Yerel değişiklik var (DİA'ya yazılmadı)")], db_index=True, default='bekliyor', max_length=20, verbose_name='Sync durumu')),
                ('dia_son_degisiklik', models.DateTimeField(blank=True, help_text='DİA _date alanından alınan son güncelleme zamanı (delta sync için)', null=True, verbose_name="DİA'da son değişiklik")),
                ('stok_kodu', models.CharField(max_length=30, unique=True, verbose_name='Stok kodu')),
                ('aciklama', models.CharField(max_length=200, verbose_name='Açıklama')),
                ('tur', models.CharField(choices=[('TCR', 'Ticari Mal'), ('HMM', 'Hammadde'), ('YRM', 'Yarı Mamul'), ('MAM', 'Mamul'), ('HZM', 'Hizmet'), ('DIG', 'Diğer')], default='TCR', max_length=5, verbose_name='Tür')),
                ('durum', models.CharField(choices=[('A', 'Aktif'), ('P', 'Pasif')], default='A', max_length=1, verbose_name='Durum')),
                ('ana_birim', models.CharField(blank=True, max_length=20, verbose_name='Ana birim')),
                ('ana_birim_dia_key', models.CharField(blank=True, max_length=20, verbose_name='Birim DİA key')),
                ('ana_barkod', models.CharField(blank=True, max_length=50, verbose_name='Ana barkod')),
                ('marka', models.CharField(blank=True, max_length=100, verbose_name='Marka')),
                ('ozel_kod1', models.CharField(blank=True, max_length=100, verbose_name='Özel kod 1')),
                ('ozel_kod2', models.CharField(blank=True, max_length=100, verbose_name='Özel kod 2')),
                ('kdv_alis', models.DecimalField(decimal_places=4, default=Decimal('18'), max_digits=7, verbose_name='KDV alış (%)')),
                ('kdv_satis', models.DecimalField(decimal_places=4, default=Decimal('18'), max_digits=7, verbose_name='KDV satış (%)')),
                ('fiyat1', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18, verbose_name='Fiyat 1')),
                ('fiyat2', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18, verbose_name='Fiyat 2')),
                ('gercek_stok', models.DecimalField(decimal_places=4, default=Decimal('0'), help_text="DİA'dan senkronize edilir, MEStakip hesaplamaz.", max_digits=18, verbose_name='Gerçek stok')),
                ('fiili_stok', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18, verbose_name='Fiili stok')),
                ('notlar', models.TextField(blank=True, verbose_name='Notlar')),
                ('olusturuldu', models.DateTimeField(auto_now_add=True)),
                ('guncellendi', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Stok Kartı',
                'verbose_name_plural': 'Stok Kartları',
                'ordering': ['stok_kodu'],
                'indexes': [models.Index(fields=['stok_kodu'], name='erp_stokkar_stok_ko_688570_idx'), models.Index(fields=['ana_barkod'], name='erp_stokkar_ana_bar_919b41_idx'), models.Index(fields=['marka'], name='erp_stokkar_marka_8b4650_idx'), models.Index(fields=['durum'], name='erp_stokkar_durum_cac1c9_idx')],
            },
        ),
        migrations.CreateModel(
            name='StokDepoMiktari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gercek_miktar', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18, verbose_name='Gerçek miktar')),
                ('fiili_miktar', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18, verbose_name='Fiili miktar')),
                ('son_sync', models.DateTimeField(auto_now=True, verbose_name='Son sync')),
                ('depo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stok_miktarlari', to='erp.depo', verbose_name='Depo')),
                ('stok', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depo_miktarlari', to='erp.stokkart', verbose_name='Stok kartı')),
            ],
            options={
                'verbose_name': 'Stok Depo Miktarı',
                'verbose_name_plural': 'Stok Depo Miktarları',
                'ordering': ['stok', 'depo'],
                'unique_together': {('stok', 'depo')},
            },
        ),
    ]
