# Generated by Django 5.1.4 on 2026-07-14 11:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_depo_stokkart_stokdepomiktari'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DepoFisi',
            fields=[
                ('fis_no', models.AutoField(primary_key=True, serialize=False, verbose_name='Fiş No')),
                ('tarih', models.DateField(auto_now_add=True, verbose_name='Tarih')),
                ('plaka', models.CharField(blank=True, max_length=20, verbose_name='Plaka')),
                ('cari', models.CharField(blank=True, max_length=200, verbose_name='Cari')),
                ('adet', models.PositiveIntegerField(default=1, verbose_name='Adet')),
                ('aciklama', models.TextField(blank=True, verbose_name='Açıklama')),
                ('yazildi', models.BooleanField(default=False, verbose_name='Yazıldı?')),
                ('durum', models.CharField(choices=[('bekliyor', 'Bekliyor'), ('onaylandi', 'Onaylandı'), ('iptal', 'İptal')], default='bekliyor', max_length=15, verbose_name='Durum')),
                ('olusturuldu', models.DateTimeField(auto_now_add=True)),
                ('guncellendi', models.DateTimeField(auto_now=True)),
                ('depo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp.depo', verbose_name='Depo')),
                ('islem_yapan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='İşlem Yapan')),
            ],
            options={
                'verbose_name': 'Depo Fişi',
                'verbose_name_plural': 'Depo Fişleri',
                'ordering': ['-olusturuldu'],
            },
        ),
        migrations.CreateModel(
            name='DepoFisiKalemi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adet', models.PositiveIntegerField(default=1, verbose_name='Adet')),
                ('kalem_notu', models.CharField(blank=True, max_length=200, verbose_name='Not')),
                ('fis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kalemler', to='erp.depofisi', verbose_name='Fiş')),
                ('stok', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.stokkart', verbose_name='Stok Kartı')),
            ],
            options={
                'verbose_name': 'Depo Fişi Kalemi',
                'verbose_name_plural': 'Depo Fişi Kalemleri',
            },
        ),
    ]
