# Generated by Django 5.1.4 on 2026-07-14 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_depofisi_depofisikalemi'),
    ]

    operations = [
        migrations.AddField(
            model_name='depofisi',
            name='arac_marka',
            field=models.CharField(blank=True, max_length=50, verbose_name='Araç Marka'),
        ),
        migrations.AddField(
            model_name='depofisi',
            name='arac_model',
            field=models.CharField(blank=True, max_length=50, verbose_name='Araç Model'),
        ),
        migrations.AddField(
            model_name='depofisi',
            name='kilometre',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Kilometre'),
        ),
    ]
