# Generated by Django 5.1.4 on 2026-07-15 06:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0004_depofisi_arac_marka_depofisi_arac_model_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='depofisi',
            name='fatura_no',
            field=models.CharField(blank=True, max_length=50, verbose_name='Fatura No'),
        ),
        migrations.AddField(
            model_name='depofisi',
            name='onay_tarihi',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Onay Tarihi'),
        ),
        migrations.AddField(
            model_name='depofisi',
            name='onay_veren',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onaylanan_fisler', to=settings.AUTH_USER_MODEL, verbose_name='Onay Veren'),
        ),
        migrations.AddField(
            model_name='depofisi',
            name='onaylandi',
            field=models.BooleanField(default=False, verbose_name='Onaylandı'),
        ),
    ]
