# Generated by Django 5.1.4 on 2026-07-15 10:11

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0005_depofisi_fatura_no_depofisi_onay_tarihi_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_key', models.CharField(blank=True, db_index=True, help_text="DİA ERP'deki kaydın _key değeri. Henüz senkronize edilmediyse boş.", max_length=50, null=True, unique=True, verbose_name='DİA Key')),
                ('son_sync_tarihi', models.DateTimeField(blank=True, null=True, verbose_name='Son senkronizasyon')),
                ('sync_durumu', models.CharField(choices=[('senkron', 'Senkron (DİA ile uyumlu)'), ('bekliyor', 'Bekliyor (senkronize edilmedi)'), ('isleniyor', 'İşleniyor'), ('hatali', 'Hatalı (son sync başarısız)'), ('yerel', "Yerel değişiklik var (DİA'ya yazılmadı)")], db_index=True, default='bekliyor', max_length=20, verbose_name='Sync durumu')),
                ('dia_son_degisiklik', models.DateTimeField(blank=True, help_text='DİA _date alanından alınan son güncelleme zamanı (delta sync için)', null=True, verbose_name="DİA'da son değişiklik")),
                ('fis_no', models.CharField(blank=True, max_length=30, verbose_name='Fiş No')),
                ('belge_no', models.CharField(blank=True, max_length=50, verbose_name='Belge No')),
                ('tarih', models.DateField(blank=True, null=True, verbose_name='Tarih')),
                ('saat', models.CharField(blank=True, max_length=10, verbose_name='Saat')),
                ('tur', models.CharField(choices=[('S', 'Satış'), ('A', 'Alış'), ('I', 'İade'), ('D', 'Diğer')], default='S', max_length=1, verbose_name='Tür')),
                ('tur_aciklama', models.CharField(blank=True, max_length=50, verbose_name='Tür Açıklama')),
                ('cari_kodu', models.CharField(blank=True, max_length=30, verbose_name='Cari Kodu')),
                ('cari_unvan', models.CharField(blank=True, max_length=200, verbose_name='Cari Ünvan')),
                ('toplam', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18, verbose_name='Toplam')),
                ('net', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18, verbose_name='Net')),
                ('indirim', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18, verbose_name='İndirim')),
                ('depo_adi', models.CharField(blank=True, max_length=100, verbose_name='Depo')),
                ('sube_adi', models.CharField(blank=True, max_length=100, verbose_name='Şube')),
                ('aciklama', models.TextField(blank=True, verbose_name='Açıklama')),
                ('olusturuldu', models.DateTimeField(auto_now_add=True)),
                ('guncellendi', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fatura',
                'verbose_name_plural': 'Faturalar',
                'ordering': ['-tarih', '-fis_no'],
                'indexes': [models.Index(fields=['tarih'], name='erp_fatura_tarih_02cbfd_idx'), models.Index(fields=['tur'], name='erp_fatura_tur_9014b7_idx'), models.Index(fields=['cari_kodu'], name='erp_fatura_cari_ko_0953bf_idx')],
            },
        ),
    ]
