# Generated by Django 5.1.4 on 2026-07-15 10:59

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0006_fatura'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaturaKalemi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_key', models.CharField(blank=True, db_index=True, max_length=20)),
                ('sirano', models.PositiveSmallIntegerField(default=0, verbose_name='Sıra No')),
                ('stok_kodu', models.CharField(blank=True, max_length=30, verbose_name='Stok Kodu')),
                ('stok_adi', models.CharField(blank=True, max_length=200, verbose_name='Ürün Adı')),
                ('miktar', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18, verbose_name='Miktar')),
                ('birim', models.CharField(blank=True, max_length=20, verbose_name='Birim')),
                ('birim_fiyat', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18, verbose_name='Birim Fiyat')),
                ('indirim', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=7, verbose_name='İskonto %')),
                ('tutar', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18, verbose_name='Tutar')),
                ('satisci', models.CharField(blank=True, max_length=100, verbose_name='Satış Temsilcisi')),
                ('odeme_plani', models.CharField(blank=True, max_length=100, verbose_name='Ödeme Planı')),
                ('depo', models.CharField(blank=True, max_length=100, verbose_name='Ambar')),
                ('marka', models.CharField(blank=True, max_length=100, verbose_name='Marka')),
                ('kategori', models.CharField(blank=True, max_length=100, verbose_name='Kategori')),
                ('mevsim', models.CharField(blank=True, max_length=50, verbose_name='Mevsim')),
                ('fatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kalemler', to='erp.fatura')),
            ],
            options={
                'verbose_name': 'Fatura Kalemi',
                'verbose_name_plural': 'Fatura Kalemleri',
                'ordering': ['fatura', 'sirano'],
            },
        ),
    ]
