# Generated by Django 5.1.4 on 2026-07-15 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0007_faturakalemi'),
    ]

    operations = [
        migrations.AddField(
            model_name='faturakalemi',
            name='dot',
            field=models.CharField(blank=True, max_length=20, verbose_name='DOT / Yıl'),
        ),
    ]
