# Generated by Django 4.2.16 on 2026-07-13 07:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaBaglanti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(help_text='Örn: "Meslas Demo", "Meslas Production"', max_length=100, verbose_name='Bağlantı adı')),
                ('sunucu_kodu', models.CharField(help_text="DİA URL'sindeki sunucu kodu (örn: diademo)", max_length=50, verbose_name='Sunucu kodu')),
                ('kullanici_adi', models.CharField(max_length=100, verbose_name='Kullanıcı adı')),
                ('sifre_maskelenmiş', models.CharField(blank=True, help_text="Görüntüleme amaçlı; gerçek şifre .env'den okunur.", max_length=100, verbose_name='Şifre (maskelenmiş)')),
                ('firma_kodu', models.CharField(max_length=20, verbose_name='Firma kodu')),
                ('donem_kodu', models.CharField(max_length=20, verbose_name='Dönem kodu')),
                ('session_id', models.CharField(blank=True, max_length=255, verbose_name='Session ID')),
                ('session_alindi', models.DateTimeField(blank=True, null=True, verbose_name='Session alınma zamanı')),
                ('firma_donem_bilgisi', models.JSONField(blank=True, default=dict, help_text='sis_yetkili_firma_donem_sube_depo yanıtından önbelleğe alınan veri', verbose_name='Firma/dönem/şube/depo bilgisi')),
                ('firma_donem_guncellendi', models.DateTimeField(blank=True, null=True, verbose_name='Firma/dönem bilgisi güncellenme zamanı')),
                ('is_aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('olusturuldu', models.DateTimeField(auto_now_add=True)),
                ('guncellendi', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'DİA Bağlantı',
                'verbose_name_plural': 'DİA Bağlantılar',
                'ordering': ['-is_aktif', 'ad'],
            },
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modul', models.CharField(help_text='Örn: cari, stok, fatura, irsaliye', max_length=50, verbose_name='Modül')),
                ('baslangic', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Başlangıç')),
                ('bitis', models.DateTimeField(blank=True, null=True, verbose_name='Bitiş')),
                ('durum', models.CharField(choices=[('calisiyor', 'Çalışıyor'), ('basarili', 'Başarılı'), ('kismi_basarili', 'Kısmen Başarılı'), ('basarisiz', 'Başarısız')], default='calisiyor', max_length=20, verbose_name='Durum')),
                ('tetikleyen', models.CharField(choices=[('otomatik', 'Otomatik (zamanlanmış)'), ('manuel', 'Manuel (kullanıcı)'), ('sistem', 'Sistem (management command)')], default='sistem', max_length=20, verbose_name='Tetikleyen')),
                ('toplam_kayit', models.PositiveIntegerField(default=0, verbose_name='Toplam kayıt')),
                ('basarili_kayit', models.PositiveIntegerField(default=0, verbose_name='Başarılı kayıt')),
                ('hatali_kayit', models.PositiveIntegerField(default=0, verbose_name='Hatalı kayıt')),
                ('hata_mesaji', models.TextField(blank=True, verbose_name='Genel hata mesajı')),
                ('celery_task_id', models.CharField(blank=True, max_length=255, verbose_name='Celery task ID')),
                ('tetikleyen_kullanici', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Tetikleyen kullanıcı')),
            ],
            options={
                'verbose_name': 'Senkronizasyon Logu',
                'verbose_name_plural': 'Senkronizasyon Logları',
                'ordering': ['-baslangic'],
            },
        ),
        migrations.CreateModel(
            name='SyncHataKaydi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modul', models.CharField(max_length=50, verbose_name='Modül')),
                ('yerel_model', models.CharField(help_text='Örn: erp.Cari', max_length=100, verbose_name='Yerel model adı')),
                ('yerel_id', models.CharField(max_length=50, verbose_name='Yerel kayıt ID')),
                ('dia_servis', models.CharField(help_text='Örn: scf_carikart_ekle', max_length=100, verbose_name='DİA servis adı')),
                ('hata_kodu', models.CharField(blank=True, max_length=20, verbose_name='Hata kodu')),
                ('hata_mesaji', models.TextField(verbose_name='Hata mesajı')),
                ('deneme_sayisi', models.PositiveSmallIntegerField(default=1, verbose_name='Deneme sayısı')),
                ('olusturuldu', models.DateTimeField(auto_now_add=True)),
                ('sync_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hatalar', to='dia_integration.synclog', verbose_name='Sync logu')),
            ],
            options={
                'verbose_name': 'Sync Hata Kaydı',
                'verbose_name_plural': 'Sync Hata Kayıtları',
                'ordering': ['-olusturuldu'],
            },
        ),
        migrations.CreateModel(
            name='SenkronKuyrugu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modul', models.CharField(max_length=50, verbose_name='Modül')),
                ('islem_tipi', models.CharField(choices=[('dia_dan_cek', "DİA'dan çek (okuma)"), ('dia_ya_yaz', "DİA'ya yaz (oluştur/güncelle)"), ('dia_dan_sil', "DİA'dan sil")], max_length=20, verbose_name='İşlem tipi')),
                ('yerel_model', models.CharField(max_length=100, verbose_name='Yerel model adı')),
                ('yerel_id', models.CharField(max_length=50, verbose_name='Yerel kayıt ID')),
                ('dia_key', models.CharField(blank=True, help_text='Güncelleme/silme işlemlerinde dolu olur', max_length=50, verbose_name='DİA key')),
                ('durum', models.CharField(choices=[('bekliyor', 'Bekliyor'), ('isleniyor', 'İşleniyor'), ('tamamlandi', 'Tamamlandı'), ('basarisiz', 'Başarısız (max deneme aşıldı)'), ('iptal', 'İptal edildi')], default='bekliyor', max_length=20, verbose_name='Durum')),
                ('deneme_sayisi', models.PositiveSmallIntegerField(default=0, verbose_name='Deneme sayısı')),
                ('max_deneme', models.PositiveSmallIntegerField(default=3, verbose_name='Maksimum deneme')),
                ('sonraki_deneme', models.DateTimeField(blank=True, null=True, verbose_name='Sıradaki deneme zamanı')),
                ('son_hata', models.TextField(blank=True, verbose_name='Son hata mesajı')),
                ('ek_veri', models.JSONField(blank=True, default=dict, help_text='Görevin ihtiyaç duyduğu ek parametreler', verbose_name='Ek veri')),
                ('olusturuldu', models.DateTimeField(auto_now_add=True)),
                ('guncellendi', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Senkron Kuyruğu',
                'verbose_name_plural': 'Senkron Kuyrukları',
                'ordering': ['sonraki_deneme', 'olusturuldu'],
                'indexes': [models.Index(fields=['durum', 'sonraki_deneme'], name='dia_integra_durum_3de3a2_idx'), models.Index(fields=['modul', 'durum'], name='dia_integra_modul_a6a1f4_idx')],
            },
        ),
        migrations.CreateModel(
            name='ApiIstekLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servis_adi', models.CharField(help_text='Örn: scf_carikart_listele', max_length=100, verbose_name='Servis adı')),
                ('http_metod', models.CharField(default='POST', max_length=10, verbose_name='HTTP metod')),
                ('istek_zamani', models.DateTimeField(default=django.utils.timezone.now, verbose_name='İstek zamanı')),
                ('sure_ms', models.PositiveIntegerField(blank=True, null=True, verbose_name='Süre (ms)')),
                ('http_durum_kodu', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='HTTP durum kodu')),
                ('dia_durum_kodu', models.PositiveSmallIntegerField(blank=True, help_text='Yanıttaki status/code alanı', null=True, verbose_name='DİA durum kodu')),
                ('basarili', models.BooleanField(default=True, verbose_name='Başarılı')),
                ('hata_mesaji', models.TextField(blank=True, verbose_name='Hata mesajı')),
                ('istek_ozeti', models.JSONField(blank=True, default=dict, help_text='Filtreler, limit/offset gibi meta bilgiler; hassas veri içermemeli', verbose_name='İstek özeti')),
                ('sonuc_sayisi', models.PositiveIntegerField(blank=True, null=True, verbose_name='Dönen kayıt sayısı')),
            ],
            options={
                'verbose_name': 'API İstek Logu',
                'verbose_name_plural': 'API İstek Logları',
                'ordering': ['-istek_zamani'],
                'indexes': [models.Index(fields=['servis_adi', 'istek_zamani'], name='dia_integra_servis__69b827_idx'), models.Index(fields=['basarili'], name='dia_integra_basaril_564992_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='synclog',
            index=models.Index(fields=['modul', 'baslangic'], name='dia_integra_modul_73440c_idx'),
        ),
        migrations.AddIndex(
            model_name='synclog',
            index=models.Index(fields=['durum'], name='dia_integra_durum_ed5c16_idx'),
        ),
    ]
