# Generated by Django 5.1.4 on 2025-11-20 11:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_transaction_sanal_pos'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='banka_havale',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Banka Havale'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('event_reminder', 'Etkinlik Hatırlatıcısı'), ('event_start', 'Etkinlik Başlangıcı'), ('event_created', 'Etkinlik Oluşturuldu'), ('system', 'Sistem Bildirimi'), ('info', 'Bilgi'), ('warning', 'Uyarı'), ('error', 'Hata')], default='info', max_length=20, verbose_name='Tür'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='kasa_adi',
            field=models.CharField(choices=[('servis', 'Servis'), ('merkez-satis', 'Merkez Satış')], default='servis', max_length=20, verbose_name='Kasa Adı'),
        ),
    ]
