# Generated by Django 5.1.4 on 2025-11-24 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_transaction_banka_havale_alter_notification_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='kasa_adi',
            field=models.CharField(choices=[('servis', 'Servis'), ('merkez-satis', 'Merkez Satış'), ('virman', 'Virman')], default='servis', max_length=20, verbose_name='Kasa Adı'),
        ),
    ]
