# Generated by Django 5.1.4 on 2025-12-11 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_alter_transaction_kasa_adi'),
    ]

    operations = [
        migrations.AddField(
            model_name='siparis',
            name='musteri_aciklama',
            field=models.TextField(blank=True, null=True, verbose_name='MÜŞTERİ AÇIKLAMA'),
        ),
        migrations.AddField(
            model_name='siparis',
            name='musteri_adi',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='MÜŞTERİ ADI'),
        ),
        migrations.AddField(
            model_name='siparis',
            name='musteri_telefon',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='MÜŞTERİ TELEFON'),
        ),
        migrations.AlterField(
            model_name='siparis',
            name='odeme',
            field=models.CharField(choices=[('kredi-karti', 'Kredi Kartı'), ('havale', 'Havale'), ('cari-hesap', 'Cari Hesap'), ('banka-havale', 'Banka Havale'), ('sanal-pos', 'Sanal POS')], max_length=20, verbose_name='ÖDEME'),
        ),
    ]
