# Generated by Django 5.1.4 on 2025-12-11 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_siparis_musteri_aciklama_siparis_musteri_adi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siparis',
            name='musteri_odeme_sekli',
            field=models.CharField(blank=True, choices=[('kredi-karti', 'Kredi Kartı'), ('havale', 'Havale'), ('cari-hesap', 'Cari Hesap'), ('banka-havale', 'Banka Havale'), ('sanal-pos', 'Sanal POS')], max_length=20, null=True, verbose_name='MÜŞTERİ ÖDEME ŞEKLİ'),
        ),
    ]
