# Generated by Django 5.1.4 on 2025-12-12 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_siparis_musteri_odeme_sekli'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siparis',
            name='musteri_odeme_sekli',
        ),
        migrations.AddField(
            model_name='siparis',
            name='musteri_odeme_tutari',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='MÜŞTERİ ÖDEME TUTARI'),
        ),
    ]
