# Generated by Django 5.1.4 on 2025-12-17 09:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_remove_siparis_musteri_odeme_sekli_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='pafgo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Pafgo'),
        ),
    ]
