# Generated by Django 5.1.4 on 2025-12-23 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_transaction_pafgo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siparis',
            name='durum',
            field=models.CharField(choices=[('yolda', 'Yolda'), ('islemde', 'İşleme Devam Ediyor'), ('teslim', 'Teslim Edildi'), ('kontrol', 'Kontrol Edildi'), ('iptal', 'İptal Edildi'), ('yolda-fatura-islendi', 'Yolda/Fatura İşlendi'), ('takilacak-faturasi-islendi', 'Takılacak/Faturası İşlendi')], default='yolda', max_length=30, verbose_name='DURUM'),
        ),
    ]
