# Generated by Django 5.1.4 on 2025-12-23 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_alter_siparis_durum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siparis',
            name='odeme',
            field=models.CharField(choices=[('kredi-karti', 'Kredi Kartı'), ('havale', 'Havale'), ('cari', 'Cari')], default='cari', max_length=20, verbose_name='ÖDEME'),
        ),
    ]
