# Generated by Django 5.1.4 on 2025-12-24 15:25

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0027_alter_siparis_odeme'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CikmaLastik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('musteri_adi', models.CharField(max_length=200, verbose_name='Müşteri Adı')),
                ('musteri_telefon', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon')),
                ('musteri_plaka', models.CharField(blank=True, max_length=20, null=True, verbose_name='Araç Plakası')),
                ('marka', models.CharField(max_length=100, verbose_name='Marka')),
                ('model', models.CharField(blank=True, max_length=100, null=True, verbose_name='Model')),
                ('ebat', models.CharField(max_length=50, verbose_name='Ebat (örn: 205/55R16)')),
                ('mevsim', models.CharField(choices=[('kis', 'Kış'), ('yaz', 'Yaz'), ('dort-mevsim', '4 Mevsim')], max_length=20, verbose_name='Mevsim')),
                ('arac_tipi', models.CharField(choices=[('binek', 'Binek'), ('ticari', 'Ticari'), ('motosiklet', 'Motosiklet')], default='binek', max_length=20, verbose_name='Araç Tipi')),
                ('adet', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Adet')),
                ('durum', models.CharField(choices=[('cikti', 'Çıktı'), ('depolandi', 'Depolandı'), ('satildi', 'Satıldı'), ('imha', 'İmha Edildi')], default='cikti', max_length=20, verbose_name='Durum')),
                ('diş_derinligi', models.CharField(blank=True, max_length=50, null=True, verbose_name='Diş Derinliği (mm)')),
                ('kalite_notu', models.CharField(blank=True, max_length=20, null=True, verbose_name='Kalite (1-10)')),
                ('hasar_durumu', models.TextField(blank=True, null=True, verbose_name='Hasar Durumu')),
                ('tahmini_deger', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Tahmini Değer')),
                ('satis_fiyati', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Satış Fiyatı')),
                ('aciklama', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('depo_konumu', models.CharField(blank=True, max_length=100, null=True, verbose_name='Depo Konumu')),
                ('cikis_tarihi', models.DateField(default=django.utils.timezone.now, verbose_name='Çıkış Tarihi')),
                ('satis_tarihi', models.DateField(blank=True, null=True, verbose_name='Satış Tarihi')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Kayıt Tarihi')),
                ('guncelleme_tarihi', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cikma_lastikler', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Çıkma Lastik',
                'verbose_name_plural': 'Çıkma Lastikler',
                'ordering': ['-cikis_tarihi', '-olusturma_tarihi'],
            },
        ),
    ]
