# Generated by Django 5.1.4 on 2025-12-26 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0028_cikmalastik'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cikmalastik',
            name='kalite_notu',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Kalite (1-5)'),
        ),
    ]
