# Generated by Django 5.1.4 on 2025-12-27 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0029_alter_cikmalastik_kalite_notu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cikmalastik',
            name='kalite_notu',
            field=models.CharField(blank=True, choices=[('cok-iyi', 'Çok İyi'), ('iyi', 'İyi'), ('orta', 'Orta')], max_length=20, null=True, verbose_name='Kalite'),
        ),
    ]
