# Generated by Django 5.1.4 on 2025-12-27 14:40

from django.db import migrations


def convert_kalite_data(apps, schema_editor):
    """Convert existing kalite_notu values from numbers to new text choices"""
    CikmaLastik = apps.get_model('dashboard', 'CikmaLastik')
    
    # Mapping from old numeric values to new text values
    conversion_map = {
        '1': 'orta',      # 1-2 -> Orta (kırmızı)
        '2': 'orta',
        '3': 'iyi',       # 3 -> İyi (sarı)
        '4': 'cok-iyi',   # 4-5 -> Çok İyi (yeşil)
        '5': 'cok-iyi',
    }
    
    for lastik in CikmaLastik.objects.all():
        if lastik.kalite_notu and lastik.kalite_notu in conversion_map:
            lastik.kalite_notu = conversion_map[lastik.kalite_notu]
            lastik.save()


def reverse_convert_kalite_data(apps, schema_editor):
    """Reverse conversion - convert back to numeric values"""
    CikmaLastik = apps.get_model('dashboard', 'CikmaLastik')
    
    # Reverse mapping
    reverse_map = {
        'orta': '2',
        'iyi': '3',
        'cok-iyi': '5',
    }
    
    for lastik in CikmaLastik.objects.all():
        if lastik.kalite_notu and lastik.kalite_notu in reverse_map:
            lastik.kalite_notu = reverse_map[lastik.kalite_notu]
            lastik.save()


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0030_update_kalite_choices'),
    ]

    operations = [
        migrations.RunPython(convert_kalite_data, reverse_convert_kalite_data),
    ]
