# Generated by Django 5.1.4 on 2025-12-31 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0031_convert_kalite_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('yonetici', 'Yönetici'), ('misafir', 'Misafir')], default='yonetici', max_length=20, verbose_name='Rol'),
        ),
    ]
