# Generated by Django 5.1.4 on 2026-01-02 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0035_revert_durum_choices_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siparis',
            name='durum',
            field=models.CharField(choices=[('islemde-faturasi-islendi', 'İşlem devam ediyor/Faturası İşlendi'), ('yolda', 'Yolda'), ('islemde', 'İşlem Beklemede'), ('teslim', 'Teslim Edildi'), ('kontrol', 'Kontrol Edildi'), ('iptal', 'İptal Edildi'), ('yolda-fatura-islendi', 'Yolda/Fatura İşlendi'), ('takilacak-faturasi-islendi', 'Takılacak/Faturası İşlendi')], default='yolda', max_length=30, verbose_name='DURUM'),
        ),
    ]
