# Generated by Django 5.1.4 on 2026-01-03 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0037_revert_durum_choices_order_final'),
    ]

    operations = [
        migrations.AddField(
            model_name='malzemehareketi',
            name='kategori',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
