# Generated by Django 5.1.4 on 2026-01-04 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0038_malzemehareketi_kategori'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='kasa_adi',
            field=models.CharField(choices=[('servis', 'Servis'), ('merkez-satis', 'Merkez Satış'), ('virman', 'Virman'), ('joker-satis', 'Joker Satış')], default='servis', max_length=20, verbose_name='Kasa Adı'),
        ),
    ]
