# Generated by Django 5.1.4 on 2026-01-05 08:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0039_alter_transaction_kasa_adi'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JokerSatisDosya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosya_adi', models.CharField(max_length=200, verbose_name='Dosya Adı')),
                ('yukleme_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Yükleme Tarihi')),
                ('kullanici', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Yükleyen Kullanıcı')),
            ],
            options={
                'verbose_name': 'Joker Satış Dosyası',
                'verbose_name_plural': 'Joker Satış Dosyaları',
                'ordering': ['-yukleme_tarihi'],
            },
        ),
        migrations.CreateModel(
            name='JokerSatisHareketi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarih', models.DateField(verbose_name='Tarih')),
                ('faturano', models.CharField(max_length=100, verbose_name='Fatura No')),
                ('musteri', models.CharField(max_length=255, verbose_name='Müşteri')),
                ('kategori', models.CharField(blank=True, max_length=255, null=True, verbose_name='Kategori')),
                ('urun', models.CharField(max_length=255, verbose_name='Ürün')),
                ('tutar', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Tutar')),
                ('odeme_sekli', models.CharField(max_length=100, verbose_name='Ödeme Şekli')),
                ('eklenme_zamani', models.DateTimeField(auto_now_add=True, verbose_name='Eklenme Zamanı')),
                ('dosya', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='satirlar', to='dashboard.jokersatisdosya', verbose_name='Dosya')),
                ('kullanici', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Ekleyen Kullanıcı')),
            ],
            options={
                'verbose_name': 'Joker Satış Hareketi',
                'verbose_name_plural': 'Joker Satış Hareketleri',
                'ordering': ['-tarih', '-eklenme_zamani'],
            },
        ),
    ]
