# Generated by Django 5.1.4 on 2026-01-05 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0040_jokersatisdosya_jokersatishareketi'),
    ]

    operations = [
        migrations.AddField(
            model_name='jokersatishareketi',
            name='alis_fiyati',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Alış Fiyatı'),
        ),
        migrations.AddField(
            model_name='jokersatishareketi',
            name='kar_tutari',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Kar Tutarı'),
        ),
        migrations.AddField(
            model_name='jokersatishareketi',
            name='miktar',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Miktar'),
        ),
        migrations.AddField(
            model_name='jokersatishareketi',
            name='satis_fiyati',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Satış Fiyatı'),
        ),
    ]
