# Generated by Django 5.1.4 on 2026-01-05 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0041_jokersatishareketi_alis_fiyati_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jokersatishareketi',
            name='kategori',
        ),
        migrations.RemoveField(
            model_name='jokersatishareketi',
            name='musteri',
        ),
        migrations.RemoveField(
            model_name='jokersatishareketi',
            name='odeme_sekli',
        ),
        migrations.AddField(
            model_name='jokersatishareketi',
            name='kz',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='KZ'),
        ),
    ]
