# Generated by Django 5.1.4 on 2026-01-05 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0042_remove_jokersatishareketi_kategori_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jokersatishareketi',
            name='tutar',
        ),
        migrations.AddField(
            model_name='jokersatishareketi',
            name='urun_kodu',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ürün Kodu'),
        ),
    ]
