# Generated by Django 5.1.4 on 2026-01-05 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0043_remove_jokersatishareketi_tutar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jokersatishareketi',
            name='urun_kodu',
        ),
    ]
