# Generated by Django 5.1.4 on 2026-01-05 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0044_remove_jokersatishareketi_urun_kodu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jokersatishareketi',
            name='urun',
        ),
    ]
