# Generated by Django 5.1.4 on 2026-01-05 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0045_remove_jokersatishareketi_urun'),
    ]

    operations = [
        migrations.AddField(
            model_name='jokersatishareketi',
            name='urun',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ürün'),
        ),
    ]
