# Generated by Django 5.1.4 on 2026-01-05 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0046_jokersatishareketi_urun'),
    ]

    operations = [
        migrations.AddField(
            model_name='jokersatishareketi',
            name='cari',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Cari'),
        ),
        migrations.AddField(
            model_name='jokersatishareketi',
            name='kategori',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Kategori'),
        ),
        migrations.AddField(
            model_name='jokersatishareketi',
            name='marka',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Marka'),
        ),
        migrations.AddField(
            model_name='jokersatishareketi',
            name='urun_kodu',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ürün Kodu'),
        ),
    ]
