# Generated by Django 5.1.4 on 2026-01-05 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0047_jokersatishareketi_cari_jokersatishareketi_kategori_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jokersatishareketi',
            name='faturano',
        ),
        migrations.RemoveField(
            model_name='jokersatishareketi',
            name='kz',
        ),
    ]
