# Generated by Django 5.1.4 on 2026-01-14 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0048_remove_jokersatishareketi_faturano_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siparis',
            name='mevsim',
            field=models.CharField(blank=True, choices=[('kis', 'Kış'), ('yaz', 'Yaz'), ('dort-mevsim', '4 Mevsim')], max_length=20, null=True, verbose_name='MEVSİM'),
        ),
    ]
