# Generated by Django 5.1.4 on 2026-01-16 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0049_alter_siparis_mevsim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cikmalastik',
            name='kalite_notu',
            field=models.CharField(blank=True, choices=[('100', '%100'), ('95', '%95'), ('90', '%90'), ('85', '%85'), ('80', '%80'), ('75', '%75'), ('70', '%70'), ('65', '%65'), ('60', '%60'), ('55', '%55'), ('50', '%50')], max_length=20, null=True, verbose_name='Kalite'),
        ),
    ]
