# Generated by Django 5.1.4 on 2026-01-16 08:45

from django.db import migrations


def convert_kalite_values(apps, schema_editor):
    """Eski kalite değerlerini yeni yüzdelik sisteme çevir"""
    CikmaLastik = apps.get_model('dashboard', 'CikmaLastik')
    
    # Eski değerleri yeni değerlere eşle
    kalite_mapping = {
        'cok-iyi': '100',
        'iyi': '85',
        'orta': '70',
    }
    
    for lastik in CikmaLastik.objects.all():
        if lastik.kalite_notu in kalite_mapping:
            lastik.kalite_notu = kalite_mapping[lastik.kalite_notu]
            lastik.save()


def reverse_kalite_values(apps, schema_editor):
    """Geri alma işlemi - yüzdelik değerleri eski sisteme çevir"""
    CikmaLastik = apps.get_model('dashboard', 'CikmaLastik')
    
    # Yeni değerleri eski değerlere eşle
    reverse_mapping = {
        '100': 'cok-iyi',
        '95': 'cok-iyi',
        '90': 'cok-iyi',
        '85': 'iyi',
        '80': 'iyi',
        '75': 'iyi',
        '70': 'orta',
        '65': 'orta',
        '60': 'orta',
        '55': 'orta',
        '50': 'orta',
    }
    
    for lastik in CikmaLastik.objects.all():
        if lastik.kalite_notu in reverse_mapping:
            lastik.kalite_notu = reverse_mapping[lastik.kalite_notu]
            lastik.save()


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0050_alter_cikmalastik_kalite_notu'),
    ]

    operations = [
        migrations.RunPython(convert_kalite_values, reverse_kalite_values),
    ]
