# Generated by Django 5.1.4 on 2026-02-05 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0051_auto_20260116_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='malzemehareketi',
            name='ref',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='REF'),
        ),
    ]
