# Generated by Django 5.1.4 on 2026-02-16 09:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0052_malzemehareketi_ref'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teklif_no', models.CharField(max_length=50, unique=True, verbose_name='Teklif No')),
                ('durum', models.CharField(choices=[('acik', 'Açık Teklif'), ('onaylandi', 'Onaylı'), ('reddedildi', 'Reddedildi')], default='acik', max_length=20, verbose_name='Durum')),
                ('cari', models.CharField(max_length=200, verbose_name='Cari')),
                ('ilgili_kisi', models.CharField(blank=True, max_length=200, null=True, verbose_name='İlgili Kişi')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('odeme_sekli', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ödeme Şekli')),
                ('aciklama', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('teklif_tarihi', models.DateField(verbose_name='Teklif Tarihi')),
                ('gecerlilik_tarihi', models.DateField(blank=True, null=True, verbose_name='Son Geçerlilik Tarihi')),
                ('ara_toplam', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Ara Toplam (KDV Hariç)')),
                ('kdv_tutari', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='KDV Tutarı')),
                ('genel_toplam', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Genel Toplam')),
                ('rezerve', models.BooleanField(default=False, verbose_name='Rezerve')),
                ('proforma', models.BooleanField(default=False, verbose_name='Proforma')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('guncelleme_tarihi', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('olusturan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='olusturulan_teklifler', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
            ],
            options={
                'verbose_name': 'Teklif',
                'verbose_name_plural': 'Teklifler',
                'ordering': ['-olusturma_tarihi'],
            },
        ),
        migrations.CreateModel(
            name='QuotationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urun_adi', models.CharField(max_length=300, verbose_name='Ürün/Hizmet Adı')),
                ('miktar', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Miktar')),
                ('birim_fiyat', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Birim Fiyat (KDV Dahil)')),
                ('toplam', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Toplam')),
                ('sira', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('teklif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urunler', to='dashboard.quotation', verbose_name='Teklif')),
            ],
            options={
                'verbose_name': 'Teklif Kalemi',
                'verbose_name_plural': 'Teklif Kalemleri',
                'ordering': ['sira'],
            },
        ),
    ]
