# Generated by Django 5.1.4 on 2026-02-16 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0053_quotation_quotationitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationitem',
            name='marka',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Marka'),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='mevsim',
            field=models.CharField(blank=True, choices=[('kis', 'Kış'), ('yaz', 'Yaz'), ('dort-mevsim', '4 Mevsim')], max_length=20, null=True, verbose_name='Mevsim'),
        ),
    ]
