# Generated by Django 5.1.4 on 2026-02-17 10:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0054_quotationitem_marka_quotationitem_mevsim'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GarantiBelgesi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('belge_no', models.CharField(max_length=50, unique=True, verbose_name='Belge No')),
                ('musteri_adi', models.CharField(max_length=200, verbose_name='Müşteri Adı/Ünvan')),
                ('musteri_telefon', models.CharField(max_length=20, verbose_name='Müşteri Telefon')),
                ('arac_plaka', models.CharField(max_length=20, verbose_name='Araç Plaka')),
                ('arac_marka_model', models.CharField(max_length=200, verbose_name='Araç Marka/Model')),
                ('arac_yil', models.CharField(blank=True, max_length=10, null=True, verbose_name='Araç Yıl')),
                ('arac_km', models.CharField(blank=True, max_length=20, null=True, verbose_name='Araç Km')),
                ('montaj_tarihi', models.DateField(verbose_name='Montaj Tarihi')),
                ('notlar', models.TextField(blank=True, null=True, verbose_name='Notlar')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('guncelleme_tarihi', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('olusturan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='olusturulan_garanti_belgeleri', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
            ],
            options={
                'verbose_name': 'Garanti Belgesi',
                'verbose_name_plural': 'Garanti Belgeleri',
                'ordering': ['-olusturma_tarihi'],
            },
        ),
        migrations.CreateModel(
            name='GarantiBelgesiLastik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marka', models.CharField(max_length=100, verbose_name='Marka')),
                ('ebat', models.CharField(max_length=100, verbose_name='Ebat')),
                ('adet', models.PositiveIntegerField(default=1, verbose_name='Adet')),
                ('sira', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('belge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lastikler', to='dashboard.garantibelgesi', verbose_name='Garanti Belgesi')),
            ],
            options={
                'verbose_name': 'Garanti Belgesi Lastik',
                'verbose_name_plural': 'Garanti Belgesi Lastikler',
                'ordering': ['sira'],
            },
        ),
    ]
