# Generated by Django 5.1.4 on 2026-02-17 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0055_garantibelgesi_garantibelgesilastik'),
    ]

    operations = [
        migrations.AddField(
            model_name='garantibelgesilastik',
            name='fiyat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Fiyat'),
        ),
    ]
