# Generated by Django 5.1.4 on 2026-02-17 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0056_garantibelgesilastik_fiyat'),
    ]

    operations = [
        migrations.AddField(
            model_name='cikmalastik',
            name='canta',
            field=models.BooleanField(default=False, verbose_name='Çanta'),
        ),
        migrations.AddField(
            model_name='cikmalastik',
            name='cari',
            field=models.BooleanField(default=False, verbose_name='Cari'),
        ),
        migrations.AddField(
            model_name='cikmalastik',
            name='mehmet_havale',
            field=models.BooleanField(default=False, verbose_name='Mehmet Havale'),
        ),
    ]
