# Generated by Django 5.1.4 on 2026-02-18 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0057_cikmalastik_canta_cikmalastik_cari_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='snooze_count',
            field=models.IntegerField(default=0, verbose_name='Erteleme Sayısı'),
        ),
        migrations.AddField(
            model_name='notification',
            name='snoozed_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ertelenme Zamanı'),
        ),
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('reminder', 'Hatırlatıcı')], default='reminder', max_length=20, verbose_name='Tür'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('pending', 'Bekliyor'), ('sent', 'Gönderildi'), ('read', 'Okundu'), ('dismissed', 'Kapatıldı'), ('snoozed', 'Ertelendi')], default='pending', max_length=20, verbose_name='Durum'),
        ),
    ]
