# Generated by Django 5.1.4 on 2026-02-27 08:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0058_notification_snooze_count_notification_snoozed_until_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='canta_cikis',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Çanta Çıkış'),
        ),
    ]
