# Generated by Django 5.1.4 on 2026-03-25 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0059_transaction_canta_cikis'),
    ]

    operations = [
        migrations.AddField(
            model_name='malzemehareketi',
            name='marka',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
