# Generated by Django 4.2.16 on 2026-05-05 07:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0061_quotation_ic_not'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siparis',
            name='durum',
            field=models.CharField(choices=[('yolda', 'Yolda'), ('takildi-ft-islendi-islem-devam', 'Takıldı / FT İşlendi / İşlem Devam...'), ('islemde', 'Takıldı-Faturası gelmedi'), ('teslim', 'Teslim Edildi'), ('kontrol', 'Kontrol Edildi'), ('iptal', 'İptal Edildi'), ('yolda-fatura-islendi', 'Yolda/Fatura İşlendi'), ('takilacak-faturasi-islendi', 'Takılacak/Faturası İşlendi'), ('islemde-faturasi-islendi', 'İşlem devam.../Faturası İşlendi')], default='yolda', max_length=30, verbose_name='DURUM'),
        ),
        migrations.CreateModel(
            name='LastikModelBilgisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_adi', models.CharField(max_length=200, unique=True, verbose_name='Model Adı')),
                ('mevsim', models.CharField(choices=[('kis', 'Kış'), ('yaz', 'Yaz'), ('dort-mevsim', '4 Mevsim')], max_length=20, verbose_name='Mevsim')),
                ('guncelleme_sayisi', models.PositiveIntegerField(default=1, verbose_name='Güncelleme Sayısı')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('guncelleme_tarihi', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('son_guncelleyen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Son Güncelleyen')),
            ],
            options={
                'verbose_name': 'Lastik Model Bilgisi',
                'verbose_name_plural': 'Lastik Model Bilgileri',
                'ordering': ['model_adi'],
            },
        ),
    ]
