# Generated by Django 4.2.16 on 2026-09-07 07:38

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0062_lastik_model_bilgisi'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiloArac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plaka', models.CharField(max_length=20, verbose_name='Plaka')),
                ('ambar', models.CharField(choices=[('stok', 'Stok'), ('satis', 'Satış')], default='stok', max_length=20, verbose_name='Ambar')),
                ('adet', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Adet')),
                ('durum', models.CharField(choices=[('saklamada', 'Saklamada'), ('kullanicida', 'Kullanıcıya Teslim Edildi'), ('otl', 'ÖTL')], default='saklamada', max_length=20, verbose_name='Durum')),
                ('ebat', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ebat')),
                ('mevsim', models.CharField(blank=True, choices=[('kis', 'Kış'), ('yaz', 'Yaz'), ('dort-mevsim', '4 Mevsim')], max_length=20, null=True, verbose_name='Mevsim')),
                ('aciklama', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('guncelleme_tarihi', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filo_araclar', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Filo Aracı',
                'verbose_name_plural': 'Filo Araçları',
                'ordering': ['-olusturma_tarihi'],
            },
        ),
    ]
