# Generated by Django 4.2.16 on 2026-09-08 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0063_filo_arac'),
    ]

    operations = [
        migrations.AddField(
            model_name='filoarac',
            name='raf',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Raf'),
        ),
    ]
