# Generated by Django 4.2.16 on 2026-09-23 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0064_filo_arac_raf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filoarac',
            name='durum',
            field=models.CharField(choices=[('saklamada', 'Saklamada'), ('degisim_yapildi', 'Değişim Yapıldı'), ('kullanicida', 'Kullanıcıya Teslim Edildi'), ('otl', 'ÖTL')], default='saklamada', max_length=20, verbose_name='Durum'),
        ),
    ]
