# Generated by Django 4.2.16 on 2026-09-28 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0065_filo_degisim_yapildi'),
    ]

    operations = [
        migrations.AddField(
            model_name='cikmalastik',
            name='admin_aciklama',
            field=models.TextField(blank=True, default='', verbose_name='Admin Açıklaması'),
        ),
    ]
